# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/base:${BASE_VERSION} AS builder

ENV MAKEFLAGS="-j2" \
    CARGO_BUILD_JOBS=2 \
    UV_CONCURRENCY=2 \
    CC="/usr/bin/clang" \
    CXX="/usr/bin/clang++"

# Build dependencies: Python 3.14, Rust, and build tools
RUN pkg update && \
    pkg install -y \
    python314 \
    uv \
    rust \
    git-lite \
    FreeBSD-clang \
    FreeBSD-clang-dev \
    FreeBSD-toolchain \
    FreeBSD-clibs-dev \
    FreeBSD-audit-dev \
    FreeBSD-libexecinfo-dev \
    FreeBSD-runtime-dev \
    FreeBSD-utilities-dev \
    FreeBSD-openssl-dev \
    FreeBSD-zlib-dev \
    ffmpeg-nox11 \
    libffi \
    libjpeg-turbo \
    zlib-ng \
    ca_root_nss \
    zstd \
    cmake \
    ninja \
    gcc \
    gmake \
    pkgconf \
    unzip && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/* && \
    ln -s /usr/local/bin/gmake /usr/local/bin/make

# Fetch go2rtc FreBSD binary
RUN GO2RTC_VERSION=$(fetch -qo - "https://api.github.com/repos/AlexxIT/go2rtc/releases/latest" | \
        sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p') && \
    fetch -o /tmp/go2rtc.zip \
        "https://github.com/AlexxIT/go2rtc/releases/download/${GO2RTC_VERSION}/go2rtc_freebsd_amd64.zip" && \
    unzip -o /tmp/go2rtc.zip go2rtc -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/go2rtc && \
    rm /tmp/go2rtc.zip

# Create venv and install core HA package
RUN uv venv --python 3.14 /opt/hass && \
    uv pip install --python /opt/hass homeassistant zlib-ng && \
    sed -i '' 's/if not sys.platform.startswith(("darwin", "linux")):/if False:/' /opt/hass/lib/python3.14/site-packages/homeassistant/__main__.py && \
    sed -i '' 's/except AuthError as ex:/except Exception as ex:/' /opt/hass/lib/python3.14/site-packages/bluetooth_adapters/dbus.py && \
    sed -i '' 's/for adapter in self._bluez.adapter_details:/if False:  # FreeBSD: no BlueZ/' /opt/hass/lib/python3.14/site-packages/bluetooth_adapters/systems/linux.py && \
    rm -rf /root/.cache /root/.local/share/uv

RUN VERSION=$(/opt/hass/bin/python -c "import homeassistant.const; print(homeassistant.const.__version__)") && \
    fetch -o /tmp/requirements_all.txt \
        "https://raw.githubusercontent.com/home-assistant/core/${VERSION}/requirements_all.txt" && \
    grep -v '^#' /tmp/requirements_all.txt | grep -v '^$' | \
        xargs -L1 uv pip install --python /opt/hass 2>/dev/null; \
    rm -f /tmp/requirements_all.txt && \
    rm -rf /root/.cargo /root/.cache

# Capture installed version
RUN mkdir -p /app && \
    /opt/hass/bin/python -c \
    "import homeassistant.const; print(homeassistant.const.__version__)" \
    > /app/version

# Production image
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="python314 py314-sqlite3 ffmpeg-nox11 libffi libjpeg-turbo ca_root_nss pkgconf gmake cmake rust zlib-ng FreeBSD-clang FreeBSD-toolchain FreeBSD-clibs-dev FreeBSD-runtime-dev FreeBSD-utilities-dev FreeBSD-openssl-dev FreeBSD-zlib-dev git-lite"
ARG UPSTREAM_URL="https://api.github.com/repos/home-assistant/core/releases/latest"

ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:8123/api/"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

LABEL org.opencontainers.image.title="Home Assistant" \
      org.opencontainers.image.description="Home Assistant on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/home-assistant" \
      org.opencontainers.image.url="https://www.home-assistant.io/" \
      org.opencontainers.image.documentation="https://www.home-assistant.io/docs/" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.volumes="/config" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    ln -s /usr/local/bin/gmake /usr/local/bin/make && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

COPY --from=builder /opt/hass /opt/hass
COPY --from=builder /app/version /app/version
COPY --from=builder /usr/local/bin/go2rtc /usr/local/bin/go2rtc

RUN touch /.dockerenv && \
    mkdir -p /config && \
    chown -R bsd:bsd /config /opt/hass

COPY root/ /
RUN chmod +x /etc/services.d/home-assistant/run /healthz 2>/dev/null || true

ENV PATH="/opt/hass/bin:$PATH" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

VOLUME /config